/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class obo_org_obo_car_OboJni */

#ifndef _Included_obo_org_obo_car_OboJni
#define _Included_obo_org_obo_car_OboJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     obo_org_obo_car_OboJni
 * Method:    oboLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_obo_org_obo_1car_OboJni_oboLogin
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     obo_org_obo_car_OboJni
 * Method:    oboReg
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_obo_org_obo_1car_OboJni_oboReg
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
